[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/board/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/card/*"
  to = "/index.html"
  status = 200
  force = false